spring:
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: kahramanovruslan085@gmail.com
    password:
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    sender:
      email: kahramanovruslan085@gmail.com

server:
  port: 8090