spring:
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: //todo email
    password: //todo password
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    sender:
      email: //todo email

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/