spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        student-server-url: http://localhost:8081
        university-server-url: http://localhost:8082
        company-server-url: http://localhost:8083
        auth-server-url: http://localhost:8084
        review-server-url: http://localhost:8087

server:
  port: 8080

jwt:
  secret: fdf203scdjkfkds9sdnfasb8ica12039r1mjkc1a
  issuer: ruslan

cors:
    allowCredentials: false
    allowedOrigins: http://localhost:3000
    allowedMethods: GET, POST, PUT, DELETE, OPTIONS, HEAD
    allowedHeaders: origin, content-type, accept, authorization, cookie, X-User-Id, X-User-Role

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/