version: '3.8'

services:
  postgres:
    image: postgres:16.2
    container_name: student_service_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: student_service_db
      POSTGRES_USER: ruslan
      POSTGRES_PASSWORD: 12345