services:
  postgres:
    image: postgres:15
    container_name: student_service_db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: student_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: o130805o