spring:
  application:
    name: student-service
  datasource:
    url: jdbc:postgresql://localhost:5433/student_service_db
    username: ruslan
    password: 12345
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/changelog-master.yml