spring:
  application:
    name: student-service
  datasource:
    url: jdbc:postgresql://localhost:5434/student_service_db
    username: postgres
    password: o130805o
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/changelog-master.yml

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/