services:
  postgres:
    image: postgres:15
    container_name: auth_service_db
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: auth_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: o130805o